global using Carter;
global using Mapster;
global using MediatR;
global using Npgsql;
global using BuildingBlocks.CQRS;
global using Catalog.API.Data;
global using Catalog.API.Models;
global using Catalog.API.Exceptions;
global using FluentValidation;
